# Generated by Django 3.2.15 on 2022-10-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentscard', to='nippo.post')),
            ],
        ),
    ]
