# Generated by Django 3.2.15 on 2022-10-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleMpdel',
            new_name='SampleModel',
        ),
    ]
